package com.google.cloud.tools.minikube.gradle;

import com.google.cloud.tools.minikube.gradle.MinikubePlugin;
import com.google.cloud.tools.minikube.gradle.MinikubeTask;
import org.gradle.api.Project;
import org.gradle.api.internal.project.ProjectInternal;
import org.gradle.api.tasks.TaskCollection;
import org.gradle.api.tasks.TaskContainer;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.Assert;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'appu' at '6/8/17 3:08 PM' with Gradle 2.0
 *
 * @author appu, @date 6/8/17 3:08 PM
 */
public class MinikubePluginTest {
  @Rule
  public TemporaryFolder tmp = new TemporaryFolder();

  @Test
  public void testDefaultMinikubeTasks() {
    Project project = ProjectBuilder.builder().withProjectDir(tmp.getRoot()).build();
    project.getPluginManager().apply(MinikubePlugin.class);
    ((ProjectInternal) project).evaluate();

    TaskContainer t = project.getTasks();
    TaskCollection<MinikubeTask> tc = t.withType(MinikubeTask.class);

    Assert.assertEquals(2, tc.size());

    MinikubeTask minikubeStart = tc.getByName("minikubeStart");
    Assert.assertEquals(minikubeStart.getMinikube(), "minikube");
    Assert.assertEquals(minikubeStart.getCommand(), "start");
    Assert.assertArrayEquals(minikubeStart.getFlags(), new String[]{});

    MinikubeTask minikubeStop = tc.getByName("minikubeStop");
    Assert.assertEquals(minikubeStop.getMinikube(), "minikube");
    Assert.assertEquals(minikubeStop.getCommand(), "stop");
    Assert.assertArrayEquals(minikubeStop.getFlags(), new String[]{});
  }
}
